spring:
  datasource:
    url: jdbc:mariadb://localhost:3307/moviehub
    username: moviehub
    password: moviehub
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

tmdb:
  base-url: https://api.themoviedb.org/3
  api-key: ${TMDB_API_KEY}
  language: en-US

logging:
  file:
    name: logs/app.log
  level:
    root: INFO
    com.example.moviehub: DEBUG
